config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='blog/'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('easylearn.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^blog/', include('easylearn.blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

easylearn/blog/urls.py
from django.urls import include, path
from blog.views import BlogPostCreateView, BlogPostDetailView, BlogPostFeedListView, RecommendedBlogPostsListView, rate_view, comment_view, preview_view
app_name = 'blog'

urlpatterns = [
    path('write/', BlogPostCreateView.as_view(), name='write'),
    path('post/<int:pk>/',BlogPostDetailView.as_view() , name='blog_post'),
    path('post/<slug:slug>/',BlogPostDetailView.as_view() ,name='blog_post_slug'),
    path('',BlogPostFeedListView.as_view() , name='feed'),
    path('recommended/',RecommendedBlogPostsListView.as_view() , name='recommended'),
    path('<int:pk>/rate/<int:value>/',rate_view,name='rate'),
    path('<int:pk>/comment/', comment_view, name='comment'),
    path('preview/', preview_view, name='preview'),
]

easylearn/blog/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from markdown import markdown
from slugify import UniqueSlugify
from bs4 import BeautifulSoup

POST_SUMMARY_LENGTH = 250

def check_unique_slug(text, *args):
    return not BlogPost.objects.filter(slug=text).exists()

# Create your models here.
class BlogPost(models.Model):
    """Model definition for BlogPost."""

    title = models.CharField(max_length=50, blank = False)
    slug = models.SlugField(blank=True)
    text = models.TextField(blank=False, max_length=4000)
    writer = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta definition for BlogPost."""

        verbose_name = 'Blog post'
        verbose_name_plural = 'Blog posts'
        ordering = ['-create_date']

    def __str__(self):
        """Unicode representation of BlogPost."""
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            unique_slugify = UniqueSlugify(unique_check=check_unique_slug)
            self.slug = unique_slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:blog_post_slug', kwargs={'slug': self.slug})

    def get_summary(self):
        soup = BeautifulSoup(self.get_summary_as_markdown())
        summary = soup.text[:POST_SUMMARY_LENGTH]
        if len(self.text) > POST_SUMMARY_LENGTH:
            summary += '...'
        return summary
    
    def get_summary_as_markdown(self):
        return markdown(self.text)

    def get_rating_avg(self):
        result = self.Ratings.aggregate(models.Avg('value'))['value__avg']
        if not result:
            return 0
        return result


class Comment(models.Model):
    """Model definition for Comment."""

    post = models.ForeignKey(BlogPost, models.CASCADE, blank=False)
    text = models.TextField(max_length=500, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=False)

    class Meta:
        """Meta definition for Comment."""

        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ['-create_date']

    def __str__(self):
        """Unicode representation of Comment."""
        return self.text



class Rating(models.Model):
    """Model definition for Rating."""

    rate_date = models.DateTimeField(auto_now_add=True)
    rater = models.ForeignKey('users.User', on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='Ratings')
    value = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        blank=False
    )

    class Meta:
        """Meta definition for Rating."""

        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'
        unique_together = ("rater", "post")

    def __str__(self):
        """Unicode representation of Rating."""
        return '{} rates {} with {} start'.format(self.rater, self.post, self.value)


class Following(models.Model):
    """Model definition for Following."""

    follower = models.ForeignKey('users.User', on_delete=models.CASCADE, 
    related_name='followed')
    followed = models.ForeignKey('users.User', on_delete=models.CASCADE,
    related_name='followers')

    class Meta:
        """Meta definition for Following."""

        verbose_name = 'Following'
        verbose_name_plural = 'Followings'
        unique_together = ("follower", "followed")

    def __str__(self):
        """Unicode representation of Following."""
        return '{} follows {}'.format(self.follower, self.followed)
    

easylearn/blog/forms.py
from django import forms

from blog.models import BlogPost

class BlogPostForm(forms.ModelForm):
    """BlogPostForm definition."""
    text = forms.CharField(widget=forms.Textarea(attrs={'cols':100, 'class':'arabic-text', 
    'id':'post-text'}), 
    max_length=4000, required=True, label='المنشور')
    title = forms.CharField(widget = forms.TextInput(attrs={'cols':50, 'class':'arabic-text'}),
     max_length=50, required=True, label='العنوان')

    class Meta:

        model = BlogPost
        fields = ('title', 'text',)

easylearn/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest

from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import BlogPostForm
from blog.models import BlogPost, Following, Rating, Comment
from easylearn.users.models import User

from markdown import markdown


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    form_class = BlogPostForm
    template_name = "blog/write.html"
    success_url = ''

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super(BlogPostCreateView, self).form_valid(form)


class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = BlogPost
    template_name = "blog/post_details.html"
    pk_url_kwarg = 'pk'
    slug_url_kwarg = 'slug'
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        user = self.request.user
        try:
            rating = Rating.objects.get(rater=user, post=self.object)
        except Rating.DoesNotExist:
            rating_val = -1
        else:
            rating_val = rating.value
        context['rating'] = rating_val
        return context


class BlogPostFeedListView(LoginRequiredMixin, ListView):
    model = BlogPost
    template_name = "blog/post_feed.html"
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        followed_ids = user.followed.all().values_list('followed', flat=True)
        queryset = BlogPost.objects.filter(writer__in=followed_ids)
        return queryset

### Model path is in easylearn/blog/ML_model folder
def get_most_similar_articles_to_multiple_articles(list_of_arts ,
    model_path='easylearn/blog/ML_model/small model'):
    
    # loading up the model
    import os
    model_path = os.path.abspath(model_path)
    #'/media/yazan/OS/Users/Yazan/Desktop/wikilogia/Project/easylearn/easylearn/blog/ML_model/small model'
    import gensim as gs
    model = gs.models.doc2vec.Doc2Vec.load(model_path)
    
    vectors = []
    for token in list_of_arts:
        vectors.append(model.infer_vector(token))
    
    sims = model.docvecs.most_similar(vectors)
    
    def extract_id_from_slug(slug):
        s = slug.split('_')[1]
        return str(s)
    
    # here I am just converting the slug from the way it's written in the dataframe
    # to the way it's written in the database
    # this is how a slug looks in the dataframe : 'SENT_10'
    # and this is how it looks in the database : 's_10'
    convert_sent_to_s = lambda slug : 's_' + extract_id_from_slug(slug)
    
    resulted_list_of_slugs = []
    for (slug,_) in sims:
        resulted_list_of_slugs.append(convert_sent_to_s(slug))
        
    return resulted_list_of_slugs
    
class RecommendedBlogPostsListView(LoginRequiredMixin, ListView):
    model = BlogPost
    template_name = "blog/post_feed.html"

    def get_queryset(self):
        user = self.request.user
        liked_articles = Rating.objects.filter(rater=user,value__gt=2
        ).values_list('post__text', flat=True)[:10]
        token_lists = []
        for text in liked_articles:
            token_lists.append(text.split())
        slug_list = get_most_similar_articles_to_multiple_articles(token_lists)
        queryset = BlogPost.objects.filter(slug__in=slug_list)
        return queryset
        

@login_required
def follow_view(request, username):
    curent_user = request.user
    other_user = User.objects.get(username=username)
    if Following.objects.filter(follower=curent_user, followed=other_user).exists():
        return HttpResponseRedirect(other_user.get_absolute_url())

    following = Following(follower=curent_user, followed=other_user)
    following.save()
    return HttpResponseRedirect(other_user.get_absolute_url())


@login_required
def unfollow_view(request, username):
    curent_user = request.user
    other_user = User.objects.get(username=username)
    following = Following.objects.filter(follower=curent_user, followed=other_user)
    if not following.exists():
        return HttpResponseRedirect(other_user.get_absolute_url())

    following.delete()
    return HttpResponseRedirect(other_user.get_absolute_url())

@login_required
def rate_view(request, pk, value):
    user = request.user
    rating = None
    try:
        rating = Rating.objects.get(rater=user, post=pk)
    except Rating.DoesNotExist:
        rating = Rating(rater=user, post=BlogPost.objects.get(pk=pk))
    rating.value = value
    rating.save()
    return redirect(BlogPost.objects.get(pk=pk))

@login_required
def comment_view(request, pk):
    user = request.user
    post = get_object_or_404(BlogPost, pk=pk)
    try:
        text = request.POST['text']
    except KeyError:
        return HttpResponseBadRequest()
    comment = Comment(writer=user, post=post, text=text)
    comment.save()
    return redirect(post)

@login_required
def preview_view(request):
    if request.method != 'POST':
        return HttpResponseBadRequest()
    try:
        text = request.POST['text']
    except KeyError:
        return HttpResponseBadRequest()
    html_text = markdown(text)
    return render(request, 'blog/preview.html',{'text':html_text})

easylearn/blog/templates/blog/post_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_heading %}{{object.title}}{% endblock page_heading %}
{% block page_subheading %}{% endblock page_subheading %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/comments.css' %}">
<link rel="stylesheet" href="{% static 'css/rate.css' %}">
<link rel="stylesheet" href="{% static 'css/comment_block.css'%}">
{% endblock %}
{% block content %}
<article>
    <div class="container" dir="rtl">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
         {{ object.get_summary_as_markdown |safe}}
        </div>
      </div>
    </div>
  </article>

<!--rating block -->
<div class="row rate" dir="rtl">
  <div class="col-md-12">
    <div class="rating-block">
      <h4>متوسط التقييمات</h4>
      <h2 class="bold padding-bottom-7">{{object.get_rating_avg}}<small>\ 5</small></h2>

        <a href="{%url 'blog:rate' pk=object.pk value=1%}"><button type="button" class="btn btn-warning btn-sm" aria-label="Left Align" id=star-1>
          <span class="fa fa-star" aria-hidden="true"></span>
        </button></a>
        <a href="{%url 'blog:rate' pk=object.pk value=2%}"><button type="button" class="btn btn-warning btn-sm" aria-label="Left Align" id=star-2>
          <span class="fa fa-star" aria-hidden="true"></span>
        </button></a>
        <a href="{%url 'blog:rate' pk=object.pk value=3%}"><button type="button" class="btn btn-warning btn-sm" aria-label="Left Align" id=star-3>
          <span class="fa fa-star" aria-hidden="true"></span>
        </button></a>
        <a href="{%url 'blog:rate' pk=object.pk value=4%}"><button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align" id=star-4>
          <span class="fa fa-star" aria-hidden="true"></span>
        </button></a>
        <a href="{%url 'blog:rate' pk=object.pk value=5%}"><button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align" id=star-5>
          <span class="fa fa-star" aria-hidden="true"></span>
        </button></a>

    </div>
  </div>
</div>
<!--write comment -->
<div class="row" dir="rtl">
    
  <div class="col-md-6">
              <div class="widget-area no-padding blank">
              <div class="status-upload">
                <form method="POST" action="{% url 'blog:comment' object.id %}">
                    {% csrf_token %}
                  <textarea placeholder="اكتب تعليقاً" name="text"></textarea>
                  <button type="submit" class="btn btn-primary"><i class="fa fa-share"></i>انشر</button>
                </form>
              </div><!-- Status Upload  -->
              </div><!-- Widget Area -->
  </div>      
  </div>

<!-- comments -->
<section class="comments" dir="rtl">
  {% for comment in  object.comment_set.all %}
    <article class="comment">
        <div class="comment-body">
          <div class="text">
            <p>{{ comment.text }}</p>
          </div>
          <p class="attribution arabic-text">نشر من قبل 
            <a href="{{object.writer.get_absolute_url}}">
            {{comment.writer}}</a>في 
            {{comment.create_date | date:"H:i   j-n-Y"}}</p>
        </div>
      </article>
  {% endfor %}
</section>​
 
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/rate.js' %}"></script>
  <script>
    $( document ).ready(function() {
      color({{rating}});
  });
  </script>
{% endblock javascript %}

easylearn/blog/templates/blog/post_feed.html
{% extends 'base.html' %} 
{% load staticfiles %} 

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">                   
            {% for post in object_list %}
                <div class="post-preview" dir="rtl">
                    <a href="{{post.get_absolute_url}}">
                        <h2 class="post-title arabic-text">
                            {{post.title}}
                        </h2>
                        <h3 class="post-subtitle arabic-text">
                            {{post.get_summary}}
                        </h3>
                    </a>
                    <p class="post-meta arabic-text"> نشر من قبل
                        <a href="{{post.writer.get_absolute_url}}">{{post.writer.username}}</a>
                        في
                        {{post.create_date | date:"j, n, Y"}}
                    </p>
                </div>
            {% empty %}
                <h2 class="arabic-text">لا يوجد المزيد من المنشورات</h2>
            {% endfor %}

            <!-- Pager -->
            {% comment %} <div class="clearfix">
                <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
            </div> {% endcomment %}

        </div>
    </div>
    <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto"> 
        <style>
                .pagination>li>a, .pagination>li>span { border-radius: 50% !important;margin: 0 5px;}
        </style>
        <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                {% else %}
                    <li class="page-item disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
                {% endif %}
                
                {% if page_obj.number|add:'-4' > 1 %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
                {% endif %}
                
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                
                {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
                {% endif %}
                
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                {% else %}
                    <li class="page-item disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
                {% endif %}
                
                </ul>
            </div>
        </div>
</div>

{% endblock content %}

easylearn/blog/templates/blog/preview.html
{% extends "base.html" %}
{% block page_heading %}معاينة{% endblock page_heading %}
{% block page_subheading %}{% endblock page_subheading %}
{% block content %}
    <div dir="rtl">
       {{text|safe}} 
    </div>
    
{% endblock content %}
    

easylearn/blog/templates/blog/write.html
{% extends "base.html" %} {% load staticfiles %} 
{% block content %}

<div class="container-fluid" dir="rtl" <div class="container-fluid">
        <div class="row">
                <div class="">
                        <button class="btn btn-primary" id="h1-btn">
                                H1
                        </button>

                        <button class="btn btn-primary" id="h2-btn">
                                H2
                        </button>

                        <button class="btn btn-primary" id="h3-btn">
                                H3
                        </button>

                        <button class="btn btn-primary" id="bold-btn">
                                <i class="fa fa-bold"></i>
                        </button>

                        <button class="btn btn-primary" id="italic-btn">
                                <i class="fa fa-italic"></i>
                        </button>
                        <button class="btn btn-primary" id="o-list-btn">
                                <i class="fa fa-list-ol"></i>
                        </button>
                        <button class="btn btn-primary" id="u-list-btn">
                                <i class="fa fa-list-ul"></i>
                        </button>
                </div>
        </div>
        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                        <form method="POST">
                                {% csrf_token %} {{form.as_p}}
                                <button type="submit" class="btn btn-primary" onclick="$('form').removeAttr('target', '_blank');">نشر</button>
                                <button formaction="{% url 'blog:preview' %}" onclick="$('form').attr('target', '_blank');"
                                 type="submit" class="btn btn-primary">معاينة</button>
                        </form>
                </div>
        </div>
</div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="{% static 'js/write.js' %}"></script> 

{% endblock content %}




        



        